### ISSUE TITLE
Advantage of C++ implementation isOnClust, isOnClust2

### ISSUE THREAD

**Issue by jkbenotmane** [ksahlin/isONcorrect#8]
Is the C++ Implementation of isOnClust, isOnClust2 https://github.com/nanoporetech/isONclust2 equal to the Python one and compatible with the Pipeline of isOnCorrect and can it just be used as Replacement for the isOnClust step?

**Comment by ksahlin** [comment]
It should give identical or near-identical clusters to the `isONclust` implementation. They are identical algorithms but the C++ implementation is optimized for speed. 

I believe the output of `isONclust2` is compatible with isONcorrect. I remember there was a small naming conflict such as `isONclust` labeled the fastq files `0.fastq,1.dastq,..` while `isONclust2` labeled them `cluster_0.fastq, cluster_1.fastq...`. This cause a conflict if one calls `isONcorrect` with the `run_isoncorrect` multiprocessing [wrapping script/pipeline](https://github.com/ksahlin/isONcorrect#manually), but this can be easily fixed by renaming the files.

I remember raising this issue with @bsipos  developer of isONclust2 but am unsure if the file names were changed.

**Comment by jkbenotmane** [comment]
Thanks for the answer! 
Exactly that speed benefit is what I would seek for.

But isONclust2 produces .cer files from the intial sorting and clustering as explained here:

# sort reads and write out batches:
isONclust2 sort -B 50000 -v ens500.fq
# initial clustering of individual batches:
isONclust2 cluster -v -l isONclust2_batches/sorted/batches/isONbatch_0.cer -o b0.cer
isONclust2 cluster -v -l isONclust2_batches/sorted/batches/isONbatch_1.cer -o b1.cer
isONclust2 cluster -v -l isONclust2_batches/sorted/batches/isONbatch_2.cer -o b1.cer

How can you combine this with the clustering of the reads with following writing of the fastq files as needed as input for run_isoncorrect?

**Comment by ksahlin** [comment]
As read in the [`Warning` paragraph](https://github.com/nanoporetech/isONclust2), you should (probably) not run isONclust2 by itself, but instead, run it through this interface for parallelization: https://github.com/nanoporetech/pipeline-nanopore-denovo-isoforms

I'm not sure about the combining step. I would assume the output of isONclust2 was fastq files of clustered reads. At least this is the output of the [pipeline-nanopore-denovo-isoforms](https://github.com/nanoporetech/pipeline-nanopore-denovo-isoforms#output)

**Comment by jkbenotmane** [comment]
The Usage of isONClust2 through pipeline-nanopore-denovo-isoforms pipe is distinctly different, as one must parse the commandline args to a yaml file when using isONCorrect in a pipeline, but it has an enormous benefit in speed for reconstructing full reads and clustering them! 

Thanks for the advice!

**Comment by ksahlin** [comment]
Yes, a C++ implementation of isONcorrect would be great and (I predict) will allow for quite a speedup. I started such an effort but not looking to finish anytime soon due to other priorities. Hopefully, I can get someone to do this. 

As described in the README, you can use e.g. `--k 9 --w 20 --max_seqs 2000` to reduce the computational burden (both time and memory), or even larger `--w` of like 25 or 30, this will of course lead to less accurate reads.
